on:
  push:
    branches:
      - main # Default release branch
      - 'release/**'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set VERSION variable from tag
      run: echo "VERSION=1.3.0" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --configuration Release
    - name: Pack
      run: dotnet pack --configuration Release --output .
    - name: Push
      run: dotnet nuget push Osrm.HttpApiClient.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.NUGET_API_KEY }}
